language: ruby
gemfile:
  - gemfiles/rails5_0.gemfile
  - gemfiles/rails5_1.gemfile
  - gemfiles/rails5_2.gemfile
  - gemfiles/rails6_0.gemfile
rvm:
  - jruby-19mode
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.1
notifications:
  email:
    - scott@railsnewbie.com
bundler_args: --without development
services: mongodb
